name: playstation_store
description: "A Flutter app to manage PlayStation shop sessions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # إدارة الحالة
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  go_router: ^16.0.0

  # تخزين محلي


  # Firebase (أساسي + Cloud Firestore)
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.0

  # ترجمة
  easy_localization: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  easy_localization_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
